name: example
description: A reorderable_grid example project.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  reorderable_grid:
    path: ../
dev_dependencies:
  flutter_lints: ^6.0.0

